name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Build the Docker image
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
      - name: Build Docker Image
        run: |
          fullCommit="${{ github.event.commits[0].id }}" && \
          docker build . --file Dockerfile --tag wdshihaoren/pingora-ingress:"$(fullCommit: 0:7)" 
 
      - name: Push Docker Image
        run: |
          fullCommit="${{ github.event.commits[0].id }}" && \
          docker push wdshihaoren/pingora-ingress:"$(fullCommit: 0:7)" 
